[package]
name = "chaos-grid"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
fxhash = "0.2"
indicatif = { version = "0.17", features = ["rayon"] }
ndarray = "0.15"
ndarray-rand = "0.14"
rayon = "1.10"
